---
kind: Namespace
apiVersion: v1
metadata:
  name: spring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring
  namespace: spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring
  template:
    metadata:
      labels:
        app: spring
    spec:
      containers:
      - image: tsoutello/dev-java-simple-crud:1.0.0
        name: spring
        ports:
        - containerPort: 8787
        livenessProbe:
          httpGet:
              path: /dev-java-simple-crud/api/actuator/health/livenessState
              port: 8787
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
              path: /dev-java-simple-crud/api/actuator/health/readinessState
              port: 8787
          initialDelaySeconds: 60
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3
          successThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: spring
  namespace: spring
spec:
  type: LoadBalancer
  ports:
    - port: 8787
      targetPort: 8787
  selector:
    app: spring